name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'GIT_INTEGRATION/**' 

  workflow_dispatch:

jobs:
  snowflake-cicd-showcase:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup Python environment
      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install snowflake-connector-python

      # Step 4: Echo the file content (for debugging)
      - name: Show file content
        run: |
          echo "Listing directory contents:"
          ls -R $GITHUB_WORKSPACE/GIT_INTEGRATION
          echo "Displaying contents of notebook_app.py:"
          cat $GITHUB_WORKSPACE/GIT_INTEGRATION/notebook_app.py

      # Step 5: Run Python script to connect and interact with Snowflake
      - name: Run Python Script
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          echo "Starting Python script execution..."
          python $GITHUB_WORKSPACE/GIT_INTEGRATION/notebook_app.py
          echo "Python script execution completed."

      # Step 6: Debug Snowflake script execution (Optional)
      - name: Check Snowflake script result
        run: |
          echo "If there were any outputs or logs from notebook_app.py, they will appear here."
