name: snowflake-devops-demo
 
# Controls when the action will run.
on:
 push:
   branches:
     - main
   paths:
     - 'dbscripts/**' 
     - 'GIT_INTEGRATION/**'  # Include paths for the notebook files
 
 # Allows you to run this workflow manually from the Actions tab
 workflow_dispatch:
 
jobs:
 snowflake-cicd-showcase:
   runs-on: ubuntu-latest
 
   steps:
     # Step 1: Checkout repository
     - name: Checkout repository
       uses: actions/checkout@v2
 
     # Step 2: Setup Python environment
     - name: Use Python 3.8.x
       uses: actions/setup-python@v2.2.1
       with:
         python-version: 3.8.x
 
     # Step 3: Install dependencies
     - name: Install dependencies
       run: |
         echo "Installing dependencies"
         pip install schemachange papermill snowflake-connector-python
 
     # Step 4: Run schemachange
     - name: Run schemachange
       env:
         SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
         SF_USERNAME: ${{ secrets.SF_USERNAME }}
         SF_ROLE: ${{ secrets.SF_ROLE }}
         SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
         SF_DATABASE: ${{ secrets.SF_DATABASE }}
         SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
       run: |
         echo "Running schemachange"
         schemachange -f $GITHUB_WORKSPACE/migrations -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
 
     # Step 5: Execute Notebook
     - name: Execute notebook
       env:
         SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
         SF_USERNAME: ${{ secrets.SF_USERNAME }}
         SF_ROLE: ${{ secrets.SF_ROLE }}
         SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
         SF_DATABASE: ${{ secrets.SF_DATABASE }}
         SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
       run: |
         echo "Executing Jupyter Notebook"
         papermill GIT_INTEGRATION/notebook_app.ipynb NOTEBOOKS/output_notebook.ipynb \
         --kernel python3 \
         -p SF_ACCOUNT $SF_ACCOUNT \
         -p SF_USERNAME $SF_USERNAME \
         -p SF_ROLE $SF_ROLE \
         -p SF_WAREHOUSE $SF_WAREHOUSE \
         -p SF_DATABASE $SF_DATABASE \
         -p SNOWFLAKE_PASSWORD $SNOWFLAKE_PASSWORD
