name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'dbscripts/**'  # Path to your SQL files

  workflow_dispatch:

jobs:
  snowflake-cicd-showcase:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install snowsql
      - name: Install snowsql
        run: |
          curl -sL https://github.com/snowflakedb/snowsql/releases/download/v1.2.12/snowsql-1.2.12-linux_x86_64.btar.gz | tar -xz
          sudo mv snowsql /usr/local/bin/

      # Step 3: Authenticate using Snowflake credentials
      - name: Authenticate and run SQL script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}
        run: |
          echo "Running SQL script in Snowflake"
          snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD -r $SNOWFLAKE_ROLE -w $SNOWFLAKE_WAREHOUSE -d $SNOWFLAKE_DATABASE -f dbscripts/your_sql_script.sql
