name: snowflake-devops-demo

on:
  push:
    branches:
      - main
    paths:
      - 'GIT_INTEGRATION/**' 

  workflow_dispatch:

jobs:
  snowflake-cicd-showcase:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup Python environment
      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install snowflake-connector-python

      # Step 4: Run Python script to connect and interact with Snowflake
      - name: Run Python Script
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          echo "Running Python script to interact with Snowflake"
          python $GITHUB_WORKSPACE/GIT_INTEGRATION/notebook_app.py

























